name: Deploy para Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy para Cloudflare Pages
        run: npx wrangler@3 pages deploy . --project-name=estofaria-digital --branch=main --commit-dirty=true
        env:
          CLOUDFLARE_API_KEY: ${{ secrets.CF_API_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
